## Multiclass Classification with the Iris Flowers Dataset -  ANN classification

In [1]:
# importing required packages

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from tensorflow.keras import utils

from sklearn.model_selection import StratifiedKFold # for k-fold validation
from sklearn.model_selection import KFold

from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import LabelEncoder

from sklearn.pipeline import Pipeline

In [2]:
# fix random seed for reproducibility

seed = 7
np.random.seed(seed)

In [3]:
# importing the dataset

location = "C:/DevelopmentPlayground/Datasets/iris.csv"

dataset = pd.read_csv(location)

In [4]:
dataset.shape

(150, 6)

In [5]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
# Spliting the dataset into X and Y

X = dataset.iloc[:, 1:5].values
Y = dataset.iloc[:, -1].values

In [7]:
# print first 5 X and Y

print(X[0:5])
print(Y[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [8]:
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [9]:
# Encoding the class values as integers

lblencoder = LabelEncoder()
lblencoder.fit(Y)
encoded_Y = lblencoder.transform(Y)

print('Encoded Y :', encoded_Y)

Encoded Y : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [10]:
# Convert the integers to dummy variables i.e., one hot encoding

Y = utils.to_categorical(encoded_Y)
# Y = utils.to_categorical(encoded_Y)

In [11]:
print('Y : \n', Y[0:5])

Y : 
 [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [12]:
print('type(X) :', type(X))
print('type(Y) :',type(Y))

type(X) : <class 'numpy.ndarray'>
type(Y) : <class 'numpy.ndarray'>


In [13]:
print('X Shape :', X.shape)
print('Y Shape :', Y.shape)

X Shape : (150, 4)
Y Shape : (150, 3)


In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=seed)

In [15]:
# creating the model
def create_baseline_model():
    model = Sequential()
    model.add(Dense(units=8, input_dim=4, activation='relu', kernel_initializer='uniform',name='Hidden-Layer-1'))
    model.add(Dense(units=3, activation='softmax', kernel_initializer='uniform', name='Output-Layer'))
    # compile the model
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

## Manual k-Fold Cross Validation - Evaluating using sklearn

In [16]:
estimator = KerasClassifier(build_fn= create_baseline_model, epochs=200, batch_size=5, verbose=1)

In [17]:
# defining 10-fold cross validation test harness

kfold = KFold(n_splits=10, shuffle=True, random_state=seed)


In [18]:
results = cross_val_score(estimator, X_train, y_train, cv=kfold)

Epoch 1/200
18/18 [==============================] - 1s 3ms/step - loss: 1.0976 - accuracy: 0.2889
Epoch 2/200
18/18 [==============================] - 0s 2ms/step - loss: 1.0931 - accuracy: 0.3222
Epoch 3/200
18/18 [==============================] - 0s 3ms/step - loss: 1.0874 - accuracy: 0.3667
Epoch 4/200
18/18 [==============================] - 0s 3ms/step - loss: 1.0809 - accuracy: 0.3556
Epoch 5/200
18/18 [==============================] - 0s 2ms/step - loss: 1.0661 - accuracy: 0.3222
Epoch 6/200
18/18 [==============================] - 0s 2ms/step - loss: 1.0500 - accuracy: 0.4889
Epoch 7/200
18/18 [==============================] - 0s 3ms/step - loss: 1.0288 - accuracy: 0.6889
Epoch 8/200
18/18 [==============================] - 0s 3ms/step - loss: 0.9997 - accuracy: 0.7000
Epoch 9/200
18/18 [==============================] - 0s 3ms/step - loss: 0.9637 - accuracy: 0.7000
Epoch 10/200
18/18 [==============================] - 0s 3ms/step - loss: 0.9238 - accuracy: 0.7000
Epoch 11/

18/18 [==============================] - 0s 3ms/step - loss: 0.1683 - accuracy: 0.9778
Epoch 84/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1689 - accuracy: 0.9778
Epoch 85/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1673 - accuracy: 0.9778
Epoch 86/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1634 - accuracy: 0.9889
Epoch 87/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1605 - accuracy: 0.9667
Epoch 88/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1600 - accuracy: 0.9778
Epoch 89/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1569 - accuracy: 0.9778
Epoch 90/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1549 - accuracy: 0.9778
Epoch 91/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1526 - accuracy: 0.9778
Epoch 92/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1508 - accuracy: 0.9778
Epoch 93/200


18/18 [==============================] - 0s 3ms/step - loss: 0.0885 - accuracy: 0.9667
Epoch 165/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0887 - accuracy: 0.9778
Epoch 166/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0879 - accuracy: 0.9778
Epoch 167/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0873 - accuracy: 0.9778
Epoch 168/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0868 - accuracy: 0.9667
Epoch 169/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0866 - accuracy: 0.9667
Epoch 170/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0881 - accuracy: 0.9667
Epoch 171/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0865 - accuracy: 0.9778
Epoch 172/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0871 - accuracy: 0.9778
Epoch 173/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0846 - accuracy: 0.9778
Epoc

18/18 [==============================] - 0s 3ms/step - loss: 0.3630 - accuracy: 0.9222
Epoch 45/200
18/18 [==============================] - 0s 3ms/step - loss: 0.3584 - accuracy: 0.9222
Epoch 46/200
18/18 [==============================] - 0s 3ms/step - loss: 0.3534 - accuracy: 0.9222
Epoch 47/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3486 - accuracy: 0.9667
Epoch 48/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3441 - accuracy: 0.9778
Epoch 49/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3414 - accuracy: 0.9667
Epoch 50/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3359 - accuracy: 0.9556
Epoch 51/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3309 - accuracy: 0.9778
Epoch 52/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3263 - accuracy: 0.9778
Epoch 53/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3220 - accuracy: 0.9778
Epoch 54/200


18/18 [==============================] - 0s 3ms/step - loss: 0.1565 - accuracy: 0.9778
Epoch 126/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1550 - accuracy: 0.9778
Epoch 127/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1538 - accuracy: 0.9778
Epoch 128/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1530 - accuracy: 0.9778
Epoch 129/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1530 - accuracy: 0.9778
Epoch 130/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1504 - accuracy: 0.9667
Epoch 131/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1500 - accuracy: 0.9778
Epoch 132/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1495 - accuracy: 0.9667
Epoch 133/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1478 - accuracy: 0.9778
Epoch 134/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1472 - accuracy: 0.9778
Epoc

18/18 [==============================] - 0s 3ms/step - loss: 1.0474 - accuracy: 0.7111
Epoch 6/200
18/18 [==============================] - 0s 3ms/step - loss: 1.0233 - accuracy: 0.7111
Epoch 7/200
18/18 [==============================] - 0s 3ms/step - loss: 0.9939 - accuracy: 0.7111
Epoch 8/200
18/18 [==============================] - 0s 3ms/step - loss: 0.9604 - accuracy: 0.7111
Epoch 9/200
18/18 [==============================] - 0s 3ms/step - loss: 0.9235 - accuracy: 0.7111
Epoch 10/200
18/18 [==============================] - 0s 3ms/step - loss: 0.8874 - accuracy: 0.7222
Epoch 11/200
18/18 [==============================] - 0s 4ms/step - loss: 0.8467 - accuracy: 0.8778
Epoch 12/200
18/18 [==============================] - 0s 4ms/step - loss: 0.8090 - accuracy: 0.7556
Epoch 13/200
18/18 [==============================] - 0s 3ms/step - loss: 0.7698 - accuracy: 0.6889
Epoch 14/200
18/18 [==============================] - 0s 3ms/step - loss: 0.7332 - accuracy: 0.6778
Epoch 15/200
18/1

18/18 [==============================] - 0s 3ms/step - loss: 0.1801 - accuracy: 0.9556
Epoch 87/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1780 - accuracy: 0.9556
Epoch 88/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1752 - accuracy: 0.9556
Epoch 89/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1732 - accuracy: 0.9667
Epoch 90/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1743 - accuracy: 0.9667
Epoch 91/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1711 - accuracy: 0.9444
Epoch 92/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1716 - accuracy: 0.9556
Epoch 93/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1663 - accuracy: 0.9778
Epoch 94/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1656 - accuracy: 0.9778
Epoch 95/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1633 - accuracy: 0.9556
Epoch 96/200


18/18 [==============================] - 0s 3ms/step - loss: 0.1014 - accuracy: 0.9778
Epoch 168/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1061 - accuracy: 0.9778
Epoch 169/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1000 - accuracy: 0.9778
Epoch 170/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1025 - accuracy: 0.9556
Epoch 171/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0992 - accuracy: 0.9667
Epoch 172/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0992 - accuracy: 0.9778
Epoch 173/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0990 - accuracy: 0.9778
Epoch 174/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1001 - accuracy: 0.9667
Epoch 175/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0977 - accuracy: 0.9667
Epoch 176/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0981 - accuracy: 0.9778
Epoc

Epoch 48/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3277 - accuracy: 0.9778
Epoch 49/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3147 - accuracy: 0.9778
Epoch 50/200
18/18 [==============================] - 0s 3ms/step - loss: 0.3180 - accuracy: 0.9778
Epoch 51/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3077 - accuracy: 0.9778
Epoch 52/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2993 - accuracy: 0.9778
Epoch 53/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2940 - accuracy: 0.9778
Epoch 54/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2894 - accuracy: 0.9778
Epoch 55/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2829 - accuracy: 0.9778
Epoch 56/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2783 - accuracy: 0.9778
Epoch 57/200
18/18 [==============================] - 0s 3ms/step - loss: 0.2728 - accuracy: 0.9778


18/18 [==============================] - 0s 2ms/step - loss: 0.1071 - accuracy: 0.9778
Epoch 130/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1050 - accuracy: 0.9778
Epoch 131/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1043 - accuracy: 0.9667
Epoch 132/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1042 - accuracy: 0.9778
Epoch 133/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1026 - accuracy: 0.9778
Epoch 134/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1023 - accuracy: 0.9667
Epoch 135/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1019 - accuracy: 0.9667
Epoch 136/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1013 - accuracy: 0.9778
Epoch 137/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1010 - accuracy: 0.9778
Epoch 138/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0987 - accuracy: 0.9778
Epoc

18/18 [==============================] - 0s 3ms/step - loss: 0.9774 - accuracy: 0.6333
Epoch 10/200
18/18 [==============================] - 0s 3ms/step - loss: 0.9572 - accuracy: 0.6333
Epoch 11/200
18/18 [==============================] - 0s 2ms/step - loss: 0.9383 - accuracy: 0.6444
Epoch 12/200
18/18 [==============================] - 0s 2ms/step - loss: 0.9200 - accuracy: 0.6444
Epoch 13/200
18/18 [==============================] - 0s 2ms/step - loss: 0.9035 - accuracy: 0.6444
Epoch 14/200
18/18 [==============================] - 0s 3ms/step - loss: 0.8887 - accuracy: 0.6444
Epoch 15/200
18/18 [==============================] - 0s 2ms/step - loss: 0.8748 - accuracy: 0.6556
Epoch 16/200
18/18 [==============================] - 0s 3ms/step - loss: 0.8626 - accuracy: 0.6556
Epoch 17/200
18/18 [==============================] - 0s 2ms/step - loss: 0.8501 - accuracy: 0.6556
Epoch 18/200
18/18 [==============================] - 0s 2ms/step - loss: 0.8393 - accuracy: 0.6667
Epoch 19/200


18/18 [==============================] - 0s 2ms/step - loss: 0.5158 - accuracy: 0.7556
Epoch 92/200
18/18 [==============================] - 0s 3ms/step - loss: 0.5134 - accuracy: 0.7667
Epoch 93/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5112 - accuracy: 0.7556
Epoch 94/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5084 - accuracy: 0.7556
Epoch 95/200
18/18 [==============================] - 0s 3ms/step - loss: 0.5064 - accuracy: 0.7556
Epoch 96/200
18/18 [==============================] - 0s 3ms/step - loss: 0.5039 - accuracy: 0.7556
Epoch 97/200
18/18 [==============================] - 0s 3ms/step - loss: 0.5021 - accuracy: 0.7556
Epoch 98/200
18/18 [==============================] - 0s 3ms/step - loss: 0.5000 - accuracy: 0.7556
Epoch 99/200
18/18 [==============================] - 0s 3ms/step - loss: 0.4971 - accuracy: 0.7667
Epoch 100/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4955 - accuracy: 0.7889
Epoch 101/20

18/18 [==============================] - 0s 3ms/step - loss: 0.3200 - accuracy: 0.9667
Epoch 173/200
18/18 [==============================] - 0s 3ms/step - loss: 0.3170 - accuracy: 0.9667
Epoch 174/200
18/18 [==============================] - 0s 3ms/step - loss: 0.3148 - accuracy: 0.9667
Epoch 175/200
18/18 [==============================] - 0s 3ms/step - loss: 0.3131 - accuracy: 0.9667
Epoch 176/200
18/18 [==============================] - 0s 3ms/step - loss: 0.3086 - accuracy: 0.9667
Epoch 177/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3065 - accuracy: 0.9667
Epoch 178/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3043 - accuracy: 0.9667
Epoch 179/200
18/18 [==============================] - 0s 3ms/step - loss: 0.3013 - accuracy: 0.9667
Epoch 180/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2981 - accuracy: 0.9667
Epoch 181/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2961 - accuracy: 0.9667
Epoc

18/18 [==============================] - 0s 3ms/step - loss: 0.6635 - accuracy: 0.6667
Epoch 46/200
18/18 [==============================] - 0s 3ms/step - loss: 0.6591 - accuracy: 0.6667
Epoch 47/200
18/18 [==============================] - 0s 2ms/step - loss: 0.6551 - accuracy: 0.6778
Epoch 48/200
18/18 [==============================] - 0s 2ms/step - loss: 0.6504 - accuracy: 0.6667
Epoch 49/200
18/18 [==============================] - 0s 2ms/step - loss: 0.6483 - accuracy: 0.6667
Epoch 50/200
18/18 [==============================] - 0s 3ms/step - loss: 0.6425 - accuracy: 0.6778
Epoch 51/200
18/18 [==============================] - 0s 2ms/step - loss: 0.6394 - accuracy: 0.6889
Epoch 52/200
18/18 [==============================] - 0s 3ms/step - loss: 0.6343 - accuracy: 0.6778
Epoch 53/200
18/18 [==============================] - 0s 3ms/step - loss: 0.6312 - accuracy: 0.6667
Epoch 54/200
18/18 [==============================] - 0s 2ms/step - loss: 0.6273 - accuracy: 0.6889
Epoch 55/200


18/18 [==============================] - 0s 3ms/step - loss: 0.3865 - accuracy: 0.9667
Epoch 127/200
18/18 [==============================] - 0s 3ms/step - loss: 0.3813 - accuracy: 0.9667
Epoch 128/200
18/18 [==============================] - 0s 3ms/step - loss: 0.3799 - accuracy: 0.9667
Epoch 129/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3756 - accuracy: 0.9667
Epoch 130/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3729 - accuracy: 0.9667
Epoch 131/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3705 - accuracy: 0.9667
Epoch 132/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3663 - accuracy: 0.9667
Epoch 133/200
18/18 [==============================] - 0s 3ms/step - loss: 0.3634 - accuracy: 0.9667
Epoch 134/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3603 - accuracy: 0.9667
Epoch 135/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3572 - accuracy: 0.9667
Epoc

2/2 [==============================] - 0s 4ms/step - loss: 0.1847 - accuracy: 1.0000
Epoch 1/200
18/18 [==============================] - 0s 2ms/step - loss: 1.0984 - accuracy: 0.4333
Epoch 2/200
18/18 [==============================] - 0s 2ms/step - loss: 1.0953 - accuracy: 0.5111
Epoch 3/200
18/18 [==============================] - 0s 3ms/step - loss: 1.0893 - accuracy: 0.6667
Epoch 4/200
18/18 [==============================] - 0s 2ms/step - loss: 1.0800 - accuracy: 0.6889
Epoch 5/200
18/18 [==============================] - 0s 3ms/step - loss: 1.0664 - accuracy: 0.6889
Epoch 6/200
18/18 [==============================] - 0s 2ms/step - loss: 1.0475 - accuracy: 0.7333
Epoch 7/200
18/18 [==============================] - 0s 2ms/step - loss: 1.0229 - accuracy: 0.8889
Epoch 8/200
18/18 [==============================] - 0s 2ms/step - loss: 0.9940 - accuracy: 0.9333
Epoch 9/200
18/18 [==============================] - 0s 2ms/step - loss: 0.9560 - accuracy: 0.9667
Epoch 10/200
18/18 [====

18/18 [==============================] - 0s 3ms/step - loss: 0.1526 - accuracy: 0.9667
Epoch 83/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1501 - accuracy: 0.9556
Epoch 84/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1479 - accuracy: 0.9667
Epoch 85/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1482 - accuracy: 0.9556
Epoch 86/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1446 - accuracy: 0.9667
Epoch 87/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1431 - accuracy: 0.9778
Epoch 88/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1417 - accuracy: 0.9778
Epoch 89/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1400 - accuracy: 0.9667
Epoch 90/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1389 - accuracy: 0.9556
Epoch 91/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1373 - accuracy: 0.9667
Epoch 92/200


18/18 [==============================] - 0s 2ms/step - loss: 0.0897 - accuracy: 0.9667
Epoch 164/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0871 - accuracy: 0.9667
Epoch 165/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0845 - accuracy: 0.9667
Epoch 166/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0847 - accuracy: 0.9778
Epoch 167/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0840 - accuracy: 0.9778
Epoch 168/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0866 - accuracy: 0.9556
Epoch 169/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0833 - accuracy: 0.9778
Epoch 170/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0833 - accuracy: 0.9778
Epoch 171/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0827 - accuracy: 0.9778
Epoch 172/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0851 - accuracy: 0.9667
Epoc

18/18 [==============================] - 0s 2ms/step - loss: 0.2912 - accuracy: 0.9667
Epoch 44/200
18/18 [==============================] - 0s 3ms/step - loss: 0.2907 - accuracy: 0.9778
Epoch 45/200
18/18 [==============================] - 0s 3ms/step - loss: 0.2810 - accuracy: 0.9667
Epoch 46/200
18/18 [==============================] - 0s 3ms/step - loss: 0.2768 - accuracy: 0.9667
Epoch 47/200
18/18 [==============================] - 0s 3ms/step - loss: 0.2712 - accuracy: 0.9667
Epoch 48/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2659 - accuracy: 0.9667
Epoch 49/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2608 - accuracy: 0.9667
Epoch 50/200
18/18 [==============================] - 0s 3ms/step - loss: 0.2559 - accuracy: 0.9556
Epoch 51/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2515 - accuracy: 0.9556
Epoch 52/200
18/18 [==============================] - 0s 3ms/step - loss: 0.2464 - accuracy: 0.9667
Epoch 53/200


18/18 [==============================] - 0s 3ms/step - loss: 0.1125 - accuracy: 0.9778
Epoch 125/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1091 - accuracy: 0.9667
Epoch 126/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1091 - accuracy: 0.9556
Epoch 127/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1091 - accuracy: 0.9667
Epoch 128/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1067 - accuracy: 0.9667
Epoch 129/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1102 - accuracy: 0.9778
Epoch 130/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1071 - accuracy: 0.9556
Epoch 131/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1051 - accuracy: 0.9667
Epoch 132/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1071 - accuracy: 0.9667
Epoch 133/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1071 - accuracy: 0.9667
Epoc

18/18 [==============================] - 0s 3ms/step - loss: 1.0826 - accuracy: 0.3333
Epoch 5/200
18/18 [==============================] - 0s 3ms/step - loss: 1.0718 - accuracy: 0.3222
Epoch 6/200
18/18 [==============================] - 0s 3ms/step - loss: 1.0524 - accuracy: 0.5667
Epoch 7/200
18/18 [==============================] - 0s 3ms/step - loss: 1.0253 - accuracy: 0.6889
Epoch 8/200
18/18 [==============================] - 0s 3ms/step - loss: 0.9882 - accuracy: 0.7000
Epoch 9/200
18/18 [==============================] - 0s 3ms/step - loss: 0.9427 - accuracy: 0.7000
Epoch 10/200
18/18 [==============================] - 0s 2ms/step - loss: 0.8920 - accuracy: 0.7000
Epoch 11/200
18/18 [==============================] - 0s 2ms/step - loss: 0.8414 - accuracy: 0.7000
Epoch 12/200
18/18 [==============================] - 0s 3ms/step - loss: 0.7904 - accuracy: 0.7000
Epoch 13/200
18/18 [==============================] - 0s 2ms/step - loss: 0.7425 - accuracy: 0.7000
Epoch 14/200
18/18

18/18 [==============================] - 0s 3ms/step - loss: 0.1783 - accuracy: 0.9667
Epoch 87/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1727 - accuracy: 0.9556
Epoch 88/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1731 - accuracy: 0.9667
Epoch 89/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1754 - accuracy: 0.9556
Epoch 90/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1714 - accuracy: 0.9667
Epoch 91/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1657 - accuracy: 0.9667
Epoch 92/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1655 - accuracy: 0.9556
Epoch 93/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1639 - accuracy: 0.9556
Epoch 94/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1616 - accuracy: 0.9667
Epoch 95/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1599 - accuracy: 0.9667
Epoch 96/200


18/18 [==============================] - 0s 2ms/step - loss: 0.1025 - accuracy: 0.9556
Epoch 168/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1019 - accuracy: 0.9667
Epoch 169/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1028 - accuracy: 0.9556
Epoch 170/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0985 - accuracy: 0.9556
Epoch 171/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1004 - accuracy: 0.9778
Epoch 172/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0983 - accuracy: 0.9556
Epoch 173/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1002 - accuracy: 0.9667
Epoch 174/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0970 - accuracy: 0.9556
Epoch 175/200
18/18 [==============================] - 0s 2ms/step - loss: 0.0977 - accuracy: 0.9556
Epoch 176/200
18/18 [==============================] - 0s 3ms/step - loss: 0.0966 - accuracy: 0.9667
Epoc

Epoch 48/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2855 - accuracy: 0.9667
Epoch 49/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2799 - accuracy: 0.9667
Epoch 50/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2795 - accuracy: 0.9667
Epoch 51/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2719 - accuracy: 0.9667
Epoch 52/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2661 - accuracy: 0.9667
Epoch 53/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2626 - accuracy: 0.9667
Epoch 54/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2609 - accuracy: 0.9667
Epoch 55/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2537 - accuracy: 0.9667
Epoch 56/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2530 - accuracy: 0.9667
Epoch 57/200
18/18 [==============================] - 0s 2ms/step - loss: 0.2488 - accuracy: 0.9667


18/18 [==============================] - 0s 3ms/step - loss: 0.1171 - accuracy: 0.9556
Epoch 130/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1180 - accuracy: 0.9667
Epoch 131/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1171 - accuracy: 0.9556
Epoch 132/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1155 - accuracy: 0.9667
Epoch 133/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1146 - accuracy: 0.9667
Epoch 134/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1199 - accuracy: 0.9667
Epoch 135/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1187 - accuracy: 0.9667
Epoch 136/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1129 - accuracy: 0.9556
Epoch 137/200
18/18 [==============================] - 0s 2ms/step - loss: 0.1133 - accuracy: 0.9556
Epoch 138/200
18/18 [==============================] - 0s 3ms/step - loss: 0.1121 - accuracy: 0.9556
Epoc

In [19]:
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))


Baseline: 98.00% (4.00%)
